image: bjohnson/pyqgl2

before_script:
  - export PYTHONPATH=$PWD/src/python

stages:
  - test

run_tests:
  stage: test
  script:
    - cd src/python
    - coverage run -m unittest discover

after_script:
  - cd src/python
  - coverage report -m
