language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"

install:
  # Setup anaconda. See http://conda.pydata.org/docs/travis.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Create conda environment with dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy bokeh h5py jupyter scipy networkx future
  - source activate test-environment
  - conda install -c ecpy atom watchdog
  - pip install git+https://github.com/BBN-Q/QGL.git
  - pip install meta coveralls
  - export PYTHONPATH=$PYTHONPATH:$PWD/src/python
  - export BBN_MEAS_FILE="$PWD/test/test_measure.yml"

script:
  - coverage run --source=pyqgl2,qgl2 -m unittest discover

after_script:
  - coveralls

# necessary to run on new container-based infrastructure
sudo: false

cache:
  directories:
    - $HOME/download
    - $HOME/.cache/pip
