language: python
python:
  - 3.5

install:
  # Setup anaconda. See http://conda.pydata.org/docs/travis.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Create conda environment with dependencies
  - conda create -q -n test-environment python=3.5 numpy bokeh h5py jupyter scipy networkx future
  - source activate test-environment
  - pip install cppy
  - pip install git+https://github.com/nucleic/atom.git@1.0.0-dev
  - pip install watchdog coveralls

script:
  - cd src/python
  - coverage run -m unittest discover
after_script:
  - coveralls

 # necessary to run on new container-based infrastructure
 sudo: false

 cache:
   directories:
     - $HOME/download
     - $HOME/.cache/pip
