#!/usr/bin/env python
#
# Copyright 2015 - Raytheon BBN Technologies Corp.  All Rights Reserved.

"""
Implements the qgl2 processor
"""

import logging
import os
import sys

from optparse import OptionParser

# The directory that this executable lives in.
#
DIRNAME = os.path.normpath(
        os.path.abspath(os.path.dirname(sys.argv[0]) or '.'))

sys.path.append(os.path.normpath(os.path.join(DIRNAME, '..', 'python')))

def parse_args(argv):
    """
    Parse the parameters from the argv
    """

    parser = OptionParser()

    parser.add_option('-v', '--verbose',
            dest='verbose',
            default=False, action="store_true",
            help='Run in verbose mode')

    parser.add_option('-l', '--log-level',
            default=logging.WARNING, type=int,
            help='Run with the given logging level [default=%default]')

    (options, fnames) = parser.parse_args(argv)

    if len(fnames) != 2:
        print 'Error: a single input file is required'
        sys.exit(1)

    return options, fnames[1]

def main():
    (opts, input_fname) = parse_args(sys.argv)

    # do something with the opts

    # process the input file

if __name__ == '__main__':
    main()
